//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BireyselCalisma2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı
    {
        public int kullanıcıId { get; set; }
        public string kAdı { get; set; }
        public string ksifre { get; set; }
        public string adı { get; set; }
        public string soyadı { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
    }
}
