//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.tr.com.otokar.service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tr.com.otokar.service.ProjectServiceSoap")]
    public interface ProjectServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_MLZ_AV_TRANSFER", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_MLZ_AV_TRANSFER(string usr, string pwd, string I_STTRH, string I_STZMN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_MLZ_AV_TRANSFER", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_MLZ_AV_TRANSFERAsync(string usr, string pwd, string I_STTRH, string I_STZMN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_MLZ_AV_TRANSFER2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_MLZ_AV_TRANSFER2(string usr, string pwd, string I_STTRH, string I_STZMN, string I_STTRH2, string I_STZMN2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_MLZ_AV_TRANSFER2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_MLZ_AV_TRANSFER2Async(string usr, string pwd, string I_STTRH, string I_STZMN, string I_STTRH2, string I_STZMN2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_VEHICLE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ZDMS_VEHICLE(string usr, string pwd, string I_VEHICLE_CODE, string I_VIN_NO, string I_DATE_FROM, string I_SAAT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_VEHICLE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_VEHICLEAsync(string usr, string pwd, string I_VEHICLE_CODE, string I_VIN_NO, string I_DATE_FROM, string I_SAAT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_VEHICLE_CODE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ZDMS_VEHICLE_CODE(string usr, string pwd, string I_VEHICLE_CODE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_VEHICLE_CODE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_VEHICLE_CODEAsync(string usr, string pwd, string I_VEHICLE_CODE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_VEHICLE_GROUP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ZDMS_VEHICLE_GROUP(string usr, string pwd, string I_VEHICLE_GROUP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_VEHICLE_GROUP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_VEHICLE_GROUPAsync(string usr, string pwd, string I_VEHICLE_GROUP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_VEHICLE_MODEL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ZDMS_VEHICLE_MODEL(string usr, string pwd, string I_VEHICLE_MODEL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_VEHICLE_MODEL", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_VEHICLE_MODELAsync(string usr, string pwd, string I_VEHICLE_MODEL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_VEHICLE_TYPE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ZDMS_VEHICLE_TYPE(string usr, string pwd, string I_VEHICLE_TYPE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_VEHICLE_TYPE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_VEHICLE_TYPEAsync(string usr, string pwd, string I_VEHICLE_TYPE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_WEB_ORDER_CREATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZYP_SD_WEB_ORDER_CREATE(
                    string usr, 
                    string pwd, 
                    string XKUNNR, 
                    string YKUNNR, 
                    string ORD_REASON, 
                    string DOC_TYPE, 
                    string SALES_ORG, 
                    string DISTR_CHAN, 
                    string DIVISION, 
                    string MODEL, 
                    string QT_VALID_T, 
                    string DLV_PRIO, 
                    string ITEM_CATEG, 
                    string TEXT, 
                    string PURCH_NO_C, 
                    string ORDERID, 
                    string NAME, 
                    string COMPL_DLV, 
                    string PARTS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_WEB_ORDER_CREATE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_WEB_ORDER_CREATEAsync(
                    string usr, 
                    string pwd, 
                    string XKUNNR, 
                    string YKUNNR, 
                    string ORD_REASON, 
                    string DOC_TYPE, 
                    string SALES_ORG, 
                    string DISTR_CHAN, 
                    string DIVISION, 
                    string MODEL, 
                    string QT_VALID_T, 
                    string DLV_PRIO, 
                    string ITEM_CATEG, 
                    string TEXT, 
                    string PURCH_NO_C, 
                    string ORDERID, 
                    string NAME, 
                    string COMPL_DLV, 
                    string PARTS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_PRODUCT_SELECTION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_PRODUCT_SELECTION(string usr, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_PRODUCT_SELECTION", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_PRODUCT_SELECTIONAsync(string usr, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_PARAKENDE_FIYAT_LISTESI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_PARAKENDE_FIYAT_LISTESI(string usr, string pwd, string I_DATUM, string I_SAAT, string I_LISTEKODU);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_PARAKENDE_FIYAT_LISTESI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_PARAKENDE_FIYAT_LISTESIAsync(string usr, string pwd, string I_DATUM, string I_SAAT, string I_LISTEKODU);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_PARAKENDE_FIYAT_LISTESI_P", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_PARAKENDE_FIYAT_LISTESI_P(string usr, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_PARAKENDE_FIYAT_LISTESI_P", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_PARAKENDE_FIYAT_LISTESI_PAsync(string usr, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_WEB_MATERIAL_ATP2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZYP_SD_WEB_MATERIAL_ATP2(string usr, string pwd, string S_MATNR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_WEB_MATERIAL_ATP2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_WEB_MATERIAL_ATP2Async(string usr, string pwd, string S_MATNR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_GIF_KAYIT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ZDMS_GIF_KAYIT(
                    string usr, 
                    string pwd, 
                    string servissapkodu, 
                    string sasino, 
                    string formudolduran, 
                    string onayrefno, 
                    string arizakodu, 
                    string arizatr, 
                    string iscilik_toplam_tutar, 
                    string parca_toplam_tutar, 
                    string para_birimi, 
                    string matbu_evrak_no, 
                    string servis_giris_tr, 
                    string serviscikistr, 
                    string masraf_merkezi, 
                    string arizadetay, 
                    string arizadetay2, 
                    string arizakm, 
                    string pdigifi, 
                    string kampanyakodu, 
                    string musteriadi, 
                    string musteriadres, 
                    string mustel1, 
                    string mustel2, 
                    string mustfax, 
                    string plakano, 
                    string aracnotu, 
                    string kullanici, 
                    string parcalar, 
                    string onarimlar, 
                    string harcamalar, 
                    string islem_tipi, 
                    string belirti_tipi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_GIF_KAYIT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_GIF_KAYITAsync(
                    string usr, 
                    string pwd, 
                    string servissapkodu, 
                    string sasino, 
                    string formudolduran, 
                    string onayrefno, 
                    string arizakodu, 
                    string arizatr, 
                    string iscilik_toplam_tutar, 
                    string parca_toplam_tutar, 
                    string para_birimi, 
                    string matbu_evrak_no, 
                    string servis_giris_tr, 
                    string serviscikistr, 
                    string masraf_merkezi, 
                    string arizadetay, 
                    string arizadetay2, 
                    string arizakm, 
                    string pdigifi, 
                    string kampanyakodu, 
                    string musteriadi, 
                    string musteriadres, 
                    string mustel1, 
                    string mustel2, 
                    string mustfax, 
                    string plakano, 
                    string aracnotu, 
                    string kullanici, 
                    string parcalar, 
                    string onarimlar, 
                    string harcamalar, 
                    string islem_tipi, 
                    string belirti_tipi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_IRSALIYE_BILGILERI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_IRSALIYE_BILGILERI(string usr, string pwd, string VBELN, string KUNNR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_IRSALIYE_BILGILERI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_IRSALIYE_BILGILERIAsync(string usr, string pwd, string VBELN, string KUNNR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_TEKLIF_RAPORU", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_TEKLIF_RAPORU(string usr, string pwd, string I_VKORG, string I_VTWEG, string I_SPART, string I_AUART, string I_LPRIO, string I_AUGRU, string I_SASBEG, string I_SASEND, string I_KUNNR, string S_VBELN, string S_MATNR, string I_DURUM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_TEKLIF_RAPORU", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_TEKLIF_RAPORUAsync(string usr, string pwd, string I_VKORG, string I_VTWEG, string I_SPART, string I_AUART, string I_LPRIO, string I_AUGRU, string I_SASBEG, string I_SASEND, string I_KUNNR, string S_VBELN, string S_MATNR, string I_DURUM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_WEB_ORDER_DELETE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZYP_SD_WEB_ORDER_DELETE(string usr, string pwd, string SALESDOCUMENT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_WEB_ORDER_DELETE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_WEB_ORDER_DELETEAsync(string usr, string pwd, string SALESDOCUMENT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_WEB_ORDER_STATUS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZYP_SD_WEB_ORDER_STATUS(string usr, string pwd, string S_VBELV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_WEB_ORDER_STATUS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_WEB_ORDER_STATUSAsync(string usr, string pwd, string S_VBELV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_MUSTERI_BILGILERI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_MUSTERI_BILGILERI(string usr, string pwd, string pmus1, string pmus2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_MUSTERI_BILGILERI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_MUSTERI_BILGILERIAsync(string usr, string pwd, string pmus1, string pmus2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_ARAC_SATIS_BILGILERI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_ARAC_SATIS_BILGILERI(string usr, string pwd, string psatis_tr1, string saat1, string psatis_tr2, string saat2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_ARAC_SATIS_BILGILERI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_ARAC_SATIS_BILGILERIAsync(string usr, string pwd, string psatis_tr1, string saat1, string psatis_tr2, string saat2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_WEB_CREDIT_STATU_WEB3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZYP_SD_WEB_CREDIT_STATU_WEB3(string usr, string pwd, string KUNNR, string VKORG, string VTWEG, string SPART);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_WEB_CREDIT_STATU_WEB3", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_WEB_CREDIT_STATU_WEB3Async(string usr, string pwd, string KUNNR, string VKORG, string VTWEG, string SPART);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_BEDELSIZ_SIPARIS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_BEDELSIZ_SIPARIS(string usr, string pwd, string TARIH1, string SAAT1, string TARIH2, string SAAT2, string KUNNR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_BEDELSIZ_SIPARIS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_BEDELSIZ_SIPARISAsync(string usr, string pwd, string TARIH1, string SAAT1, string TARIH2, string SAAT2, string KUNNR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_RED_NEDENI_BILGILERI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_RED_NEDENI_BILGILERI(string usr, string pwd, string TARIH1, string TARIH2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_RED_NEDENI_BILGILERI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_RED_NEDENI_BILGILERIAsync(string usr, string pwd, string TARIH1, string TARIH2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_PURCH_NO_UPDATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_PURCH_NO_UPDATE(string usr, string pwd, string I_VBELV, string I_PURCH_NO_C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_PURCH_NO_UPDATE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_PURCH_NO_UPDATEAsync(string usr, string pwd, string I_VBELV, string I_PURCH_NO_C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_YP_ISKONTO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_YP_ISKONTO(string usr, string pwd, string TARIH, string I_SAAT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_YP_ISKONTO", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_YP_ISKONTOAsync(string usr, string pwd, string TARIH, string I_SAAT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_REF_IZLEME", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_REF_IZLEME(string usr, string pwd, string statu, string servissapkodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_REF_IZLEME", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_REF_IZLEMEAsync(string usr, string pwd, string statu, string servissapkodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_REF_DET", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_REF_DET(string usr, string pwd, string refno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_REF_DET", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_REF_DETAsync(string usr, string pwd, string refno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_REF_DET_ISC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_REF_DET_ISC(string usr, string pwd, string refno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_REF_DET_ISC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_REF_DET_ISCAsync(string usr, string pwd, string refno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_REF_DET_PRC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_REF_DET_PRC(string usr, string pwd, string refno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_REF_DET_PRC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_REF_DET_PRCAsync(string usr, string pwd, string refno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_GIF_IPTAL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_GIF_IPTAL(string usr, string pwd, string gif_kayitno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_GIF_IPTAL", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_GIF_IPTALAsync(string usr, string pwd, string gif_kayitno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_SD_DELIVERY_LIST", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_SD_DELIVERY_LIST(string usr, string pwd, string I_TARIH1, string I_TARIH2, string I_KUNAG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_SD_DELIVERY_LIST", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_SD_DELIVERY_LISTAsync(string usr, string pwd, string I_TARIH1, string I_TARIH2, string I_KUNAG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_BOLUM_BILGILERI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_BOLUM_BILGILERI(string usr, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_BOLUM_BILGILERI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_BOLUM_BILGILERIAsync(string usr, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_INVOICE_LIST", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZYP_SD_INVOICE_LIST(string usr, string pwd, string I_TARIH1, string I_TARIH2, string I_KUNAG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYP_SD_INVOICE_LIST", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_INVOICE_LISTAsync(string usr, string pwd, string I_TARIH1, string I_TARIH2, string I_KUNAG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_GIF_PARCA_MALIYET", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_GIF_PARCA_MALIYET(string usr, string pwd, string pgifler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_GIF_PARCA_MALIYET", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_GIF_PARCA_MALIYETAsync(string usr, string pwd, string pgifler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_KMP_PRC_MLYT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ZDMS_KMP_PRC_MLYT(string usr, string pwd, string I_BUDAT, string IT_MATNR, string I_TIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZDMS_KMP_PRC_MLYT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_KMP_PRC_MLYTAsync(string usr, string pwd, string I_BUDAT, string IT_MATNR, string I_TIP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProjectServiceSoapChannel : ODMS.tr.com.otokar.service.ProjectServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectServiceSoapClient : System.ServiceModel.ClientBase<ODMS.tr.com.otokar.service.ProjectServiceSoap>, ODMS.tr.com.otokar.service.ProjectServiceSoap {
        
        public ProjectServiceSoapClient() {
        }
        
        public ProjectServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ZDMS_MLZ_AV_TRANSFER(string usr, string pwd, string I_STTRH, string I_STZMN) {
            return base.Channel.ZDMS_MLZ_AV_TRANSFER(usr, pwd, I_STTRH, I_STZMN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_MLZ_AV_TRANSFERAsync(string usr, string pwd, string I_STTRH, string I_STZMN) {
            return base.Channel.ZDMS_MLZ_AV_TRANSFERAsync(usr, pwd, I_STTRH, I_STZMN);
        }
        
        public System.Data.DataSet ZDMS_MLZ_AV_TRANSFER2(string usr, string pwd, string I_STTRH, string I_STZMN, string I_STTRH2, string I_STZMN2) {
            return base.Channel.ZDMS_MLZ_AV_TRANSFER2(usr, pwd, I_STTRH, I_STZMN, I_STTRH2, I_STZMN2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_MLZ_AV_TRANSFER2Async(string usr, string pwd, string I_STTRH, string I_STZMN, string I_STTRH2, string I_STZMN2) {
            return base.Channel.ZDMS_MLZ_AV_TRANSFER2Async(usr, pwd, I_STTRH, I_STZMN, I_STTRH2, I_STZMN2);
        }
        
        public System.Xml.XmlNode ZDMS_VEHICLE(string usr, string pwd, string I_VEHICLE_CODE, string I_VIN_NO, string I_DATE_FROM, string I_SAAT) {
            return base.Channel.ZDMS_VEHICLE(usr, pwd, I_VEHICLE_CODE, I_VIN_NO, I_DATE_FROM, I_SAAT);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_VEHICLEAsync(string usr, string pwd, string I_VEHICLE_CODE, string I_VIN_NO, string I_DATE_FROM, string I_SAAT) {
            return base.Channel.ZDMS_VEHICLEAsync(usr, pwd, I_VEHICLE_CODE, I_VIN_NO, I_DATE_FROM, I_SAAT);
        }
        
        public System.Xml.XmlNode ZDMS_VEHICLE_CODE(string usr, string pwd, string I_VEHICLE_CODE) {
            return base.Channel.ZDMS_VEHICLE_CODE(usr, pwd, I_VEHICLE_CODE);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_VEHICLE_CODEAsync(string usr, string pwd, string I_VEHICLE_CODE) {
            return base.Channel.ZDMS_VEHICLE_CODEAsync(usr, pwd, I_VEHICLE_CODE);
        }
        
        public System.Xml.XmlNode ZDMS_VEHICLE_GROUP(string usr, string pwd, string I_VEHICLE_GROUP) {
            return base.Channel.ZDMS_VEHICLE_GROUP(usr, pwd, I_VEHICLE_GROUP);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_VEHICLE_GROUPAsync(string usr, string pwd, string I_VEHICLE_GROUP) {
            return base.Channel.ZDMS_VEHICLE_GROUPAsync(usr, pwd, I_VEHICLE_GROUP);
        }
        
        public System.Xml.XmlNode ZDMS_VEHICLE_MODEL(string usr, string pwd, string I_VEHICLE_MODEL) {
            return base.Channel.ZDMS_VEHICLE_MODEL(usr, pwd, I_VEHICLE_MODEL);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_VEHICLE_MODELAsync(string usr, string pwd, string I_VEHICLE_MODEL) {
            return base.Channel.ZDMS_VEHICLE_MODELAsync(usr, pwd, I_VEHICLE_MODEL);
        }
        
        public System.Xml.XmlNode ZDMS_VEHICLE_TYPE(string usr, string pwd, string I_VEHICLE_TYPE) {
            return base.Channel.ZDMS_VEHICLE_TYPE(usr, pwd, I_VEHICLE_TYPE);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_VEHICLE_TYPEAsync(string usr, string pwd, string I_VEHICLE_TYPE) {
            return base.Channel.ZDMS_VEHICLE_TYPEAsync(usr, pwd, I_VEHICLE_TYPE);
        }
        
        public System.Data.DataSet ZYP_SD_WEB_ORDER_CREATE(
                    string usr, 
                    string pwd, 
                    string XKUNNR, 
                    string YKUNNR, 
                    string ORD_REASON, 
                    string DOC_TYPE, 
                    string SALES_ORG, 
                    string DISTR_CHAN, 
                    string DIVISION, 
                    string MODEL, 
                    string QT_VALID_T, 
                    string DLV_PRIO, 
                    string ITEM_CATEG, 
                    string TEXT, 
                    string PURCH_NO_C, 
                    string ORDERID, 
                    string NAME, 
                    string COMPL_DLV, 
                    string PARTS) {
            return base.Channel.ZYP_SD_WEB_ORDER_CREATE(usr, pwd, XKUNNR, YKUNNR, ORD_REASON, DOC_TYPE, SALES_ORG, DISTR_CHAN, DIVISION, MODEL, QT_VALID_T, DLV_PRIO, ITEM_CATEG, TEXT, PURCH_NO_C, ORDERID, NAME, COMPL_DLV, PARTS);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_WEB_ORDER_CREATEAsync(
                    string usr, 
                    string pwd, 
                    string XKUNNR, 
                    string YKUNNR, 
                    string ORD_REASON, 
                    string DOC_TYPE, 
                    string SALES_ORG, 
                    string DISTR_CHAN, 
                    string DIVISION, 
                    string MODEL, 
                    string QT_VALID_T, 
                    string DLV_PRIO, 
                    string ITEM_CATEG, 
                    string TEXT, 
                    string PURCH_NO_C, 
                    string ORDERID, 
                    string NAME, 
                    string COMPL_DLV, 
                    string PARTS) {
            return base.Channel.ZYP_SD_WEB_ORDER_CREATEAsync(usr, pwd, XKUNNR, YKUNNR, ORD_REASON, DOC_TYPE, SALES_ORG, DISTR_CHAN, DIVISION, MODEL, QT_VALID_T, DLV_PRIO, ITEM_CATEG, TEXT, PURCH_NO_C, ORDERID, NAME, COMPL_DLV, PARTS);
        }
        
        public System.Data.DataSet ZDMS_PRODUCT_SELECTION(string usr, string pwd) {
            return base.Channel.ZDMS_PRODUCT_SELECTION(usr, pwd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_PRODUCT_SELECTIONAsync(string usr, string pwd) {
            return base.Channel.ZDMS_PRODUCT_SELECTIONAsync(usr, pwd);
        }
        
        public System.Data.DataSet ZDMS_PARAKENDE_FIYAT_LISTESI(string usr, string pwd, string I_DATUM, string I_SAAT, string I_LISTEKODU) {
            return base.Channel.ZDMS_PARAKENDE_FIYAT_LISTESI(usr, pwd, I_DATUM, I_SAAT, I_LISTEKODU);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_PARAKENDE_FIYAT_LISTESIAsync(string usr, string pwd, string I_DATUM, string I_SAAT, string I_LISTEKODU) {
            return base.Channel.ZDMS_PARAKENDE_FIYAT_LISTESIAsync(usr, pwd, I_DATUM, I_SAAT, I_LISTEKODU);
        }
        
        public System.Data.DataSet ZDMS_PARAKENDE_FIYAT_LISTESI_P(string usr, string pwd) {
            return base.Channel.ZDMS_PARAKENDE_FIYAT_LISTESI_P(usr, pwd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_PARAKENDE_FIYAT_LISTESI_PAsync(string usr, string pwd) {
            return base.Channel.ZDMS_PARAKENDE_FIYAT_LISTESI_PAsync(usr, pwd);
        }
        
        public System.Data.DataSet ZYP_SD_WEB_MATERIAL_ATP2(string usr, string pwd, string S_MATNR) {
            return base.Channel.ZYP_SD_WEB_MATERIAL_ATP2(usr, pwd, S_MATNR);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_WEB_MATERIAL_ATP2Async(string usr, string pwd, string S_MATNR) {
            return base.Channel.ZYP_SD_WEB_MATERIAL_ATP2Async(usr, pwd, S_MATNR);
        }
        
        public System.Xml.XmlNode ZDMS_GIF_KAYIT(
                    string usr, 
                    string pwd, 
                    string servissapkodu, 
                    string sasino, 
                    string formudolduran, 
                    string onayrefno, 
                    string arizakodu, 
                    string arizatr, 
                    string iscilik_toplam_tutar, 
                    string parca_toplam_tutar, 
                    string para_birimi, 
                    string matbu_evrak_no, 
                    string servis_giris_tr, 
                    string serviscikistr, 
                    string masraf_merkezi, 
                    string arizadetay, 
                    string arizadetay2, 
                    string arizakm, 
                    string pdigifi, 
                    string kampanyakodu, 
                    string musteriadi, 
                    string musteriadres, 
                    string mustel1, 
                    string mustel2, 
                    string mustfax, 
                    string plakano, 
                    string aracnotu, 
                    string kullanici, 
                    string parcalar, 
                    string onarimlar, 
                    string harcamalar, 
                    string islem_tipi, 
                    string belirti_tipi) {
            return base.Channel.ZDMS_GIF_KAYIT(usr, pwd, servissapkodu, sasino, formudolduran, onayrefno, arizakodu, arizatr, iscilik_toplam_tutar, parca_toplam_tutar, para_birimi, matbu_evrak_no, servis_giris_tr, serviscikistr, masraf_merkezi, arizadetay, arizadetay2, arizakm, pdigifi, kampanyakodu, musteriadi, musteriadres, mustel1, mustel2, mustfax, plakano, aracnotu, kullanici, parcalar, onarimlar, harcamalar, islem_tipi, belirti_tipi);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ZDMS_GIF_KAYITAsync(
                    string usr, 
                    string pwd, 
                    string servissapkodu, 
                    string sasino, 
                    string formudolduran, 
                    string onayrefno, 
                    string arizakodu, 
                    string arizatr, 
                    string iscilik_toplam_tutar, 
                    string parca_toplam_tutar, 
                    string para_birimi, 
                    string matbu_evrak_no, 
                    string servis_giris_tr, 
                    string serviscikistr, 
                    string masraf_merkezi, 
                    string arizadetay, 
                    string arizadetay2, 
                    string arizakm, 
                    string pdigifi, 
                    string kampanyakodu, 
                    string musteriadi, 
                    string musteriadres, 
                    string mustel1, 
                    string mustel2, 
                    string mustfax, 
                    string plakano, 
                    string aracnotu, 
                    string kullanici, 
                    string parcalar, 
                    string onarimlar, 
                    string harcamalar, 
                    string islem_tipi, 
                    string belirti_tipi) {
            return base.Channel.ZDMS_GIF_KAYITAsync(usr, pwd, servissapkodu, sasino, formudolduran, onayrefno, arizakodu, arizatr, iscilik_toplam_tutar, parca_toplam_tutar, para_birimi, matbu_evrak_no, servis_giris_tr, serviscikistr, masraf_merkezi, arizadetay, arizadetay2, arizakm, pdigifi, kampanyakodu, musteriadi, musteriadres, mustel1, mustel2, mustfax, plakano, aracnotu, kullanici, parcalar, onarimlar, harcamalar, islem_tipi, belirti_tipi);
        }
        
        public System.Data.DataSet ZDMS_IRSALIYE_BILGILERI(string usr, string pwd, string VBELN, string KUNNR) {
            return base.Channel.ZDMS_IRSALIYE_BILGILERI(usr, pwd, VBELN, KUNNR);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_IRSALIYE_BILGILERIAsync(string usr, string pwd, string VBELN, string KUNNR) {
            return base.Channel.ZDMS_IRSALIYE_BILGILERIAsync(usr, pwd, VBELN, KUNNR);
        }
        
        public System.Data.DataSet ZDMS_TEKLIF_RAPORU(string usr, string pwd, string I_VKORG, string I_VTWEG, string I_SPART, string I_AUART, string I_LPRIO, string I_AUGRU, string I_SASBEG, string I_SASEND, string I_KUNNR, string S_VBELN, string S_MATNR, string I_DURUM) {
            return base.Channel.ZDMS_TEKLIF_RAPORU(usr, pwd, I_VKORG, I_VTWEG, I_SPART, I_AUART, I_LPRIO, I_AUGRU, I_SASBEG, I_SASEND, I_KUNNR, S_VBELN, S_MATNR, I_DURUM);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_TEKLIF_RAPORUAsync(string usr, string pwd, string I_VKORG, string I_VTWEG, string I_SPART, string I_AUART, string I_LPRIO, string I_AUGRU, string I_SASBEG, string I_SASEND, string I_KUNNR, string S_VBELN, string S_MATNR, string I_DURUM) {
            return base.Channel.ZDMS_TEKLIF_RAPORUAsync(usr, pwd, I_VKORG, I_VTWEG, I_SPART, I_AUART, I_LPRIO, I_AUGRU, I_SASBEG, I_SASEND, I_KUNNR, S_VBELN, S_MATNR, I_DURUM);
        }
        
        public System.Data.DataSet ZYP_SD_WEB_ORDER_DELETE(string usr, string pwd, string SALESDOCUMENT) {
            return base.Channel.ZYP_SD_WEB_ORDER_DELETE(usr, pwd, SALESDOCUMENT);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_WEB_ORDER_DELETEAsync(string usr, string pwd, string SALESDOCUMENT) {
            return base.Channel.ZYP_SD_WEB_ORDER_DELETEAsync(usr, pwd, SALESDOCUMENT);
        }
        
        public System.Data.DataSet ZYP_SD_WEB_ORDER_STATUS(string usr, string pwd, string S_VBELV) {
            return base.Channel.ZYP_SD_WEB_ORDER_STATUS(usr, pwd, S_VBELV);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_WEB_ORDER_STATUSAsync(string usr, string pwd, string S_VBELV) {
            return base.Channel.ZYP_SD_WEB_ORDER_STATUSAsync(usr, pwd, S_VBELV);
        }
        
        public System.Data.DataSet ZDMS_MUSTERI_BILGILERI(string usr, string pwd, string pmus1, string pmus2) {
            return base.Channel.ZDMS_MUSTERI_BILGILERI(usr, pwd, pmus1, pmus2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_MUSTERI_BILGILERIAsync(string usr, string pwd, string pmus1, string pmus2) {
            return base.Channel.ZDMS_MUSTERI_BILGILERIAsync(usr, pwd, pmus1, pmus2);
        }
        
        public System.Data.DataSet ZDMS_ARAC_SATIS_BILGILERI(string usr, string pwd, string psatis_tr1, string saat1, string psatis_tr2, string saat2) {
            return base.Channel.ZDMS_ARAC_SATIS_BILGILERI(usr, pwd, psatis_tr1, saat1, psatis_tr2, saat2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_ARAC_SATIS_BILGILERIAsync(string usr, string pwd, string psatis_tr1, string saat1, string psatis_tr2, string saat2) {
            return base.Channel.ZDMS_ARAC_SATIS_BILGILERIAsync(usr, pwd, psatis_tr1, saat1, psatis_tr2, saat2);
        }
        
        public System.Data.DataSet ZYP_SD_WEB_CREDIT_STATU_WEB3(string usr, string pwd, string KUNNR, string VKORG, string VTWEG, string SPART) {
            return base.Channel.ZYP_SD_WEB_CREDIT_STATU_WEB3(usr, pwd, KUNNR, VKORG, VTWEG, SPART);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_WEB_CREDIT_STATU_WEB3Async(string usr, string pwd, string KUNNR, string VKORG, string VTWEG, string SPART) {
            return base.Channel.ZYP_SD_WEB_CREDIT_STATU_WEB3Async(usr, pwd, KUNNR, VKORG, VTWEG, SPART);
        }
        
        public System.Data.DataSet ZDMS_BEDELSIZ_SIPARIS(string usr, string pwd, string TARIH1, string SAAT1, string TARIH2, string SAAT2, string KUNNR) {
            return base.Channel.ZDMS_BEDELSIZ_SIPARIS(usr, pwd, TARIH1, SAAT1, TARIH2, SAAT2, KUNNR);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_BEDELSIZ_SIPARISAsync(string usr, string pwd, string TARIH1, string SAAT1, string TARIH2, string SAAT2, string KUNNR) {
            return base.Channel.ZDMS_BEDELSIZ_SIPARISAsync(usr, pwd, TARIH1, SAAT1, TARIH2, SAAT2, KUNNR);
        }
        
        public System.Data.DataSet ZDMS_RED_NEDENI_BILGILERI(string usr, string pwd, string TARIH1, string TARIH2) {
            return base.Channel.ZDMS_RED_NEDENI_BILGILERI(usr, pwd, TARIH1, TARIH2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_RED_NEDENI_BILGILERIAsync(string usr, string pwd, string TARIH1, string TARIH2) {
            return base.Channel.ZDMS_RED_NEDENI_BILGILERIAsync(usr, pwd, TARIH1, TARIH2);
        }
        
        public System.Data.DataSet ZDMS_PURCH_NO_UPDATE(string usr, string pwd, string I_VBELV, string I_PURCH_NO_C) {
            return base.Channel.ZDMS_PURCH_NO_UPDATE(usr, pwd, I_VBELV, I_PURCH_NO_C);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_PURCH_NO_UPDATEAsync(string usr, string pwd, string I_VBELV, string I_PURCH_NO_C) {
            return base.Channel.ZDMS_PURCH_NO_UPDATEAsync(usr, pwd, I_VBELV, I_PURCH_NO_C);
        }
        
        public System.Data.DataSet ZDMS_YP_ISKONTO(string usr, string pwd, string TARIH, string I_SAAT) {
            return base.Channel.ZDMS_YP_ISKONTO(usr, pwd, TARIH, I_SAAT);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_YP_ISKONTOAsync(string usr, string pwd, string TARIH, string I_SAAT) {
            return base.Channel.ZDMS_YP_ISKONTOAsync(usr, pwd, TARIH, I_SAAT);
        }
        
        public System.Data.DataSet ZDMS_REF_IZLEME(string usr, string pwd, string statu, string servissapkodu) {
            return base.Channel.ZDMS_REF_IZLEME(usr, pwd, statu, servissapkodu);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_REF_IZLEMEAsync(string usr, string pwd, string statu, string servissapkodu) {
            return base.Channel.ZDMS_REF_IZLEMEAsync(usr, pwd, statu, servissapkodu);
        }
        
        public System.Data.DataSet ZDMS_REF_DET(string usr, string pwd, string refno) {
            return base.Channel.ZDMS_REF_DET(usr, pwd, refno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_REF_DETAsync(string usr, string pwd, string refno) {
            return base.Channel.ZDMS_REF_DETAsync(usr, pwd, refno);
        }
        
        public System.Data.DataSet ZDMS_REF_DET_ISC(string usr, string pwd, string refno) {
            return base.Channel.ZDMS_REF_DET_ISC(usr, pwd, refno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_REF_DET_ISCAsync(string usr, string pwd, string refno) {
            return base.Channel.ZDMS_REF_DET_ISCAsync(usr, pwd, refno);
        }
        
        public System.Data.DataSet ZDMS_REF_DET_PRC(string usr, string pwd, string refno) {
            return base.Channel.ZDMS_REF_DET_PRC(usr, pwd, refno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_REF_DET_PRCAsync(string usr, string pwd, string refno) {
            return base.Channel.ZDMS_REF_DET_PRCAsync(usr, pwd, refno);
        }
        
        public System.Data.DataSet ZDMS_GIF_IPTAL(string usr, string pwd, string gif_kayitno) {
            return base.Channel.ZDMS_GIF_IPTAL(usr, pwd, gif_kayitno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_GIF_IPTALAsync(string usr, string pwd, string gif_kayitno) {
            return base.Channel.ZDMS_GIF_IPTALAsync(usr, pwd, gif_kayitno);
        }
        
        public System.Data.DataSet ZDMS_SD_DELIVERY_LIST(string usr, string pwd, string I_TARIH1, string I_TARIH2, string I_KUNAG) {
            return base.Channel.ZDMS_SD_DELIVERY_LIST(usr, pwd, I_TARIH1, I_TARIH2, I_KUNAG);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_SD_DELIVERY_LISTAsync(string usr, string pwd, string I_TARIH1, string I_TARIH2, string I_KUNAG) {
            return base.Channel.ZDMS_SD_DELIVERY_LISTAsync(usr, pwd, I_TARIH1, I_TARIH2, I_KUNAG);
        }
        
        public System.Data.DataSet ZDMS_BOLUM_BILGILERI(string usr, string pwd) {
            return base.Channel.ZDMS_BOLUM_BILGILERI(usr, pwd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_BOLUM_BILGILERIAsync(string usr, string pwd) {
            return base.Channel.ZDMS_BOLUM_BILGILERIAsync(usr, pwd);
        }
        
        public System.Data.DataSet ZYP_SD_INVOICE_LIST(string usr, string pwd, string I_TARIH1, string I_TARIH2, string I_KUNAG) {
            return base.Channel.ZYP_SD_INVOICE_LIST(usr, pwd, I_TARIH1, I_TARIH2, I_KUNAG);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZYP_SD_INVOICE_LISTAsync(string usr, string pwd, string I_TARIH1, string I_TARIH2, string I_KUNAG) {
            return base.Channel.ZYP_SD_INVOICE_LISTAsync(usr, pwd, I_TARIH1, I_TARIH2, I_KUNAG);
        }
        
        public System.Data.DataSet ZDMS_GIF_PARCA_MALIYET(string usr, string pwd, string pgifler) {
            return base.Channel.ZDMS_GIF_PARCA_MALIYET(usr, pwd, pgifler);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_GIF_PARCA_MALIYETAsync(string usr, string pwd, string pgifler) {
            return base.Channel.ZDMS_GIF_PARCA_MALIYETAsync(usr, pwd, pgifler);
        }
        
        public System.Data.DataSet ZDMS_KMP_PRC_MLYT(string usr, string pwd, string I_BUDAT, string IT_MATNR, string I_TIP) {
            return base.Channel.ZDMS_KMP_PRC_MLYT(usr, pwd, I_BUDAT, IT_MATNR, I_TIP);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ZDMS_KMP_PRC_MLYTAsync(string usr, string pwd, string I_BUDAT, string IT_MATNR, string I_TIP) {
            return base.Channel.ZDMS_KMP_PRC_MLYTAsync(usr, pwd, I_BUDAT, IT_MATNR, I_TIP);
        }
    }
}
